#:kivy 1.8

[AccordionItemTitle@Label]:
    text: ctx.title
    font_name: 'font/Roboto-Light.ttf' if ctx.item.collapse else 'font/Roboto-Medium.ttf'
    font_size: 20
    color: [ .17, .17, .17, 1 ] if ctx.item.collapse else ( 1, 1, 1, 1 )

    canvas.before:
        Color:
            rgb: 1, 1, 1
        BorderImage:
            source:
                ctx.item.background_normal if ctx.item.collapse else ctx.item.background_selected
            pos: self.pos
            size: self.size
        PushMatrix
        Translate:
            xy: self.center_x, self.center_y
        Rotate:
            angle: 90 if ctx.item.orientation == 'horizontal' else 0
            axis: 0, 0, 1
        Translate:
            xy: -self.center_x, -self.center_y
    canvas.after:
        PopMatrix

<Test>:
    orientation: 'vertical'
    size: root.size
    pos: root.pos

    canvas.before:
        Color:
            rgba: .93, .93, .93, 1
        BorderImage:
            pos: self.pos
            size: self.size

    BoxLayout:
        size_hint:(1, 0.15)
        orientation: 'horizontal'

        canvas.before:
            Color:
                rgba: .32, .18, .7, 1
            BorderImage:
                pos: self.pos
                size: self.size

        BoxLayout:
            size_hint: ( 0.1, 1 )

            FlatButton:
                text: '<'
                font_size: 36    
                color: (1,1,1,1)
                shadow_alpha: 0
                background_color: (0,0,0,0)

        BoxLayout:
            size_hint: ( 0.8, 1 )
            Label:
                font_name: 'font/Roboto-Light.ttf'
                font_size: 36
                text: 'Main Header'
                color: [ 1, 1, 1, 1 ]
                text_size: self.size[0], self.parent.height
                halign: 'left'
                valign: 'middle'

        BoxLayout:
            size_hint: ( 0.1, 1 )
    
    BoxLayout:
        orientation: 'horizontal'    
        size_hint:(1, 0.85)
    
        Accordion:
            size_hint: ( 0.2, 1 )
            orientation: 'vertical'

            AccordionItem:
                title: 'People'
                height: 150
                Label:
                    font_name: 'font/Roboto-Light.ttf'
                    font_size: 18
                    color: ( 0, 0, 0, 1 )
                    text: 'Things about people'
            AccordionItem:
                title: 'Marketing'
                height: 150
                Label:
                    font_name: 'font/Roboto-Light.ttf'
                    font_size: 18
                    color: ( 0, 0, 0, 1 )
                    text: 'Marketing!'
            AccordionItem:
                title: 'More'
                Label:
                    font_name: 'font/Roboto-Light.ttf'
                    font_size: 18
                    color: ( 0, 0, 0, 1 )
                    text: 'More things'

        BoxLayout:    
            size_hint: 0.4, 1
            orientation: 'vertical'
            padding: ( 10, 10, 10, 10 )
            spacing: 10
            id: mainArea

            FlatButton:
                font_name: 'font/Roboto-Light.ttf'
                text: "FlatButton"
                color: 0,0,0,.9

            FlatButton:
                font_name: 'font/Roboto-Light.ttf'
                text: "FlatButton"
                color: 0,0,0,.9
                background_color: [.25,.83,.49,1]
                background_color_down: [.133,.68,.38,1]

            FlatButton:
                font_name: 'font/Roboto-Light.ttf'
                text: "FlatButton"
                color: 0,0,0,.9
                corner_radius:5
                background_color: [.95,.8,.06,1]
                background_color_down: [.95,.61,.07,1]

            FlatButton:
                font_name: 'font/Roboto-Light.ttf'
                text: "FlatButton"
                color: 0,0,0,.9
                corner_radius:10
                background_color: [.61,.35,.81,1]
                background_color_down: [.57,.27,.67,1]

            FlatButton:
                font_name: 'font/Roboto-Light.ttf'
                text: "FlatButton"
                color: 0,0,0,.9
                corner_radius:20
                background_color: [0,1,1,1]

            FlatTextInput:
                font_name: 'font/Roboto-Light.ttf'
                text: "FlatTextInput"
                hint_text: "FlatTextInput"

            FlatTextInput:
                font_name: 'font/Roboto-Light.ttf'
                hint_text: "FlatTextInput"

            FlatTextInput:
                font_name: 'font/Roboto-Light.ttf'
                text: "FlatTextInput"
                hint_text: "FlatTextInput with blue cursor"
                cursor_color: (0,0,1,1)

            FlatTextInput:
                font_name: 'font/Roboto-Light.ttf'
                hint_text: "FlatTextInput with blue cursor"
                cursor_color: (0,0,1,1)

    
        GridLayout:
            size_hint: ( 0.1, 0.2 )
            cols: 1

            FloatingAction:
                icon: 'images/done-32.png'
                diameter: 70
                font_size: 24
                background_color: ( 1, .1, .1, 1 )
                background_color_down: ( .9, .1, .1, 1 )
                color: [1,1,1,1]

